runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

automatic_scaling:
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: video-analytics-llms-422009:us-central1:my-sql-instance

env_variables:
  CLOUD_STORAGE_BUCKET: video-analytics-llms-422009.appspot.com