steps:
- name: 'python:3.12-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update
    apt-get install -y build-essential
    pip install --upgrade pip
    pip install -r requirements.txt
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/video-llm/my-image', '.']  # Update the repository name here
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/video-llm/my-image']
